### ISSUE TITLE
Banned from Server

### ISSUE THREAD

**Issue by pooberu** [Dean2k/SARS#1]
So, I was banned from the server, I presume it was because I wanted to switch over to my alt account, rather than being in there on my main due to the fact I've been banned from a few avatar Discords already because people have caught me in there. I'm active on my alt, but I do get that it is a rule that you can't use alts in there. If there is no way I can be unbanned I'll accept that, but if there is please let me know!

**Comment by Dean2k** [comment]
No alts are allowed, i can unban your main but as for alts its a nope

**Comment by pooberu** [comment]
Alrighty! If you need my main Discord then, it's wheezin_
