### ISSUE TITLE
Still can't join server (I am so sorry for making another issue)

### ISSUE THREAD

**Issue by pooberu** [Dean2k/SARS#3]
I wrote this in the last issue that was closed, I was afraid to make another one in case I was being a bother or a nuisance, but I never got replied to. This was a few days ago, but this is what I said.
![image](https://github.com/Dean2k/SARS/assets/144723894/aceeb6e0-b1a8-4dd5-82f1-bc62bf4800c8)
If I don't rejoin on the alt could it be unbanned due to the phone number thing?

**Comment by pooberu** [comment]
Just 'till I figure out how to get my phone number unassociated with that alt account.

**Comment by Dean2k** [comment]
No, its your luck out you broke server rules, you figure it out, you're lucky your unbanned.
