### ISSUE TITLE
Problem it has currently been running very slow and it crashes.

### ISSUE THREAD

**Issue by Dex-The-Protogen** [Dean2k/SARS#7]
Just after just a few minutes of use don't know if it has to do with VRCHAT servers or not but even VRCHAT has been extremely slow.

And no it isnt my computer.

In short it is unusable on my end it also takes more than 5 minutes to open.

It was running fine 4 to 5 days ago.

**Comment by Dean2k** [comment]
The only reason this would happen is if you've got issues with cloudflare as the app checks a few values from the server first and keys etc.
