### ISSUE TITLE
Wrong Unity Version

### ISSUE THREAD

**Issue by Foopener** [Dean2k/SARS#9]
When I try hot swapping with unity 2022 it comes up with an error. Looks like this 
![image_2024-02-24_154744103](https://github.com/Dean2k/SARS/assets/161168118/74d51fc8-a244-49f1-a3a6-d582e99aef62)
Not sure what I am to do about it.

**Comment by Dean2k** [comment]
Hotswap with 2019 unity then, if this fails its an 2018 model or earlier.

**Comment by Dean2k** [comment]
then set ur unity 2019 location then, you must of set it incorrectly.

**Comment by Foopener** [comment]
I probably did that. I just re-installed the unity versions and SARS. Thanks for your help though.
